version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  wp_data: {}
